### ISSUE TITLE
When I try to convert the output html to pdf in chrome, the output is only in the middle of the second page

### ISSUE THREAD

**Issue by matoken** [flobilosaurus/vscode-asciidoc-slides#18]
When I open html/Inline html with AsciiDoc Slides with chrome and convert it to pdf by adding `?print-pdf` to the url, I get only the middle of the second page.
It is broken at the time of preview.

If I set AsciiDoc Slides to 0.5.1 and use the output html, I can convert it correctly.

My environment is Linux(Debian sid amd64), so this may be a Linux-specific problem.

i use codium 1.44.2 and AsciiDoc Slides 1.2.0.

**Comment by flobilosaurus** [comment]
@matoken  Commit 18c1c00f468bc4046a1510fd77905ab33fc8fad4 should fix issues with pdf-export. Its included in version 1.3.0 i just released...
