### ISSUE TITLE
Images outside the presentation dir don't show up

### ISSUE THREAD

**Issue by manoelcampos** [flobilosaurus/vscode-asciidoc-slides#19]
When we include an image, pointing to an upper directory, like this:

```adoc
image::../image.png[]
```

the embedded and browser preview don't  show the image.
Setting the image dir with `:imagesdir:` doesn't help.

**Comment by anb0s** [comment]
I've faced same for included [files](https://github.com/flobilosaurus/vscode-asciidoc-slides/issues/16#issuecomment-620513977)

**Comment by manoelcampos** [comment]
In fact, it seems to be some issue in my setup, because even compiling to HTML, it doesn't work anymore.

**Comment by manoelcampos** [comment]
The issue is related to the new permissions required in macOS Catalina.
It doesn't work in VS Code preview or Safari but works on other browsers.
There is some way to give the required permissions. I just don't know how.

**Comment by manoelcampos** [comment]
In fact, after manually compiling to HTML and open on Firefox or Chrome, it works.
But opening the preview URL, images are not shown, even if they are at the same directory of the adoc file. But I suppose it has to do with macOS Cataline permissions.
