### ISSUE TITLE
column syntax not working

### ISSUE THREAD

**Issue by NeoScaler** [flobilosaurus/vscode-asciidoc-slides#2]
I try to use it with asciidoc slides made for asciidoc-revealjs 4.0+, using the column syntax. But the preview does not respect the columns. Is it using an older asciidoc-revealjs version perhaps?

**Comment by flobilosaurus** [comment]
Yeah right. Didn’t saw they released a new version 3 days ago. Will update as soon as I can. Thanks for the reminder!
