### ISSUE TITLE
Support preview icon

### ISSUE THREAD

**Issue by NeoScaler** [flobilosaurus/vscode-asciidoc-slides#3]
Would be great if there would be an icon for opening the slide preview if it is an asciidoc document, like it is shown for other extension previews (Markdown Preview Enhanced for example).

**Comment by flobilosaurus** [comment]
Will do that as soon as I can. Thanks

**Comment by flobilosaurus** [comment]
Fixed with a3571dfceca2bca74401ed41590f6869bf389323
